// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proyecto1.Data;

namespace Proyecto1.Migrations
{
    [DbContext(typeof(DBEmpresa))]
    partial class DBEmpresaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Proyecto1.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Taco",
                            Email = "eduardo@gmail.com",
                            Nombre = "Eduardo",
                            Telefono = 983121592,
                            Tipo = "Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Betancourt",
                            Email = "leslie@gmail.com",
                            Nombre = "Leslie",
                            Telefono = 983123456,
                            Tipo = "habitual"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Muñoz",
                            Email = "liss@gmail.com",
                            Nombre = "Lisseth",
                            Telefono = 983123456,
                            Tipo = "Nuevo"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Vlarezo",
                            Email = "belen@gmail.com",
                            Nombre = "Belen",
                            Telefono = 983121598,
                            Tipo = "habitual"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Paucar",
                            Email = "hugo@gmail.com",
                            Nombre = "Hugo",
                            Telefono = 98314567,
                            Tipo = "Nuevo"
                        });
                });

            modelBuilder.Entity("Proyecto1.Models.Credito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Fecha_Solicitud")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Credito");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fecha_Solicitud = "24-10-2021",
                            Tipo = "Credito Directo"
                        },
                        new
                        {
                            Id = 2,
                            Fecha_Solicitud = "25-10-2021",
                            Tipo = "Pago en dos partes"
                        },
                        new
                        {
                            Id = 3,
                            Fecha_Solicitud = "26-10-2021",
                            Tipo = "Cheque"
                        },
                        new
                        {
                            Id = 4,
                            Fecha_Solicitud = "27-10-2021",
                            Tipo = "Efectivo"
                        });
                });

            modelBuilder.Entity("Proyecto1.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int>("Telefono")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "eduardo@gmail.com",
                            Estado = "Entregado",
                            Nombre = "Eduardo",
                            Telefono = 983121592,
                            Tipo = "Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            Email = "leslie@gmail.com",
                            Estado = "Pendiente de Entrega",
                            Nombre = "Leslie",
                            Telefono = 983123456,
                            Tipo = "habitual"
                        },
                        new
                        {
                            Id = 3,
                            Email = "liss@gmail.com",
                            Estado = "Entregado",
                            Nombre = "Lisseth",
                            Telefono = 983123456,
                            Tipo = "Nuevo"
                        },
                        new
                        {
                            Id = 4,
                            Email = "belen@gmail.com",
                            Estado = "Pendiente de Entrega",
                            Nombre = "Belen",
                            Telefono = 983121598,
                            Tipo = "habitual"
                        },
                        new
                        {
                            Id = 5,
                            Email = "hugo@gmail.com",
                            Estado = "Entregado",
                            Nombre = "Hugo",
                            Telefono = 98314567,
                            Tipo = "Nuevo"
                        });
                });

            modelBuilder.Entity("Proyecto1.Models.HistorialCrediticio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("DeudasActivas")
                        .HasColumnType("integer");

                    b.Property<int>("DeudasVencidas")
                        .HasColumnType("integer");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HistorialCrediticio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeudasActivas = 2,
                            DeudasVencidas = 0,
                            Puntaje = 950
                        },
                        new
                        {
                            Id = 2,
                            DeudasActivas = 1,
                            DeudasVencidas = 1,
                            Puntaje = 650
                        },
                        new
                        {
                            Id = 3,
                            DeudasActivas = 3,
                            DeudasVencidas = 0,
                            Puntaje = 820
                        },
                        new
                        {
                            Id = 4,
                            DeudasActivas = 4,
                            DeudasVencidas = 4,
                            Puntaje = 439
                        },
                        new
                        {
                            Id = 5,
                            DeudasActivas = 2,
                            DeudasVencidas = 0,
                            Puntaje = 919
                        });
                });

            modelBuilder.Entity("Proyecto1.Models.HistorialCrediticioInterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("DeudasActivas")
                        .HasColumnType("integer");

                    b.Property<int>("DeudasVencidas")
                        .HasColumnType("integer");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HistorialCrediticioInterno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeudasActivas = 1,
                            DeudasVencidas = 0,
                            Puntaje = 98
                        },
                        new
                        {
                            Id = 2,
                            DeudasActivas = 2,
                            DeudasVencidas = 1,
                            Puntaje = 89
                        },
                        new
                        {
                            Id = 3,
                            DeudasActivas = 1,
                            DeudasVencidas = 2,
                            Puntaje = 76
                        },
                        new
                        {
                            Id = 4,
                            DeudasActivas = 0,
                            DeudasVencidas = 5,
                            Puntaje = 56
                        },
                        new
                        {
                            Id = 5,
                            DeudasActivas = 1,
                            DeudasVencidas = 0,
                            Puntaje = 86
                        });
                });

            modelBuilder.Entity("Proyecto1.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Marca = "Mabe",
                            Nombre = "Refrigeradora",
                            Precio = 850.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            Marca = "GE",
                            Nombre = "Refrigeradora",
                            Precio = 1610.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            Marca = "Electrolux",
                            Nombre = "Refrigeradora",
                            Precio = 720.00m,
                            Stock = 13
                        },
                        new
                        {
                            Id = 4,
                            Marca = "Indurama",
                            Nombre = "Refrigeradora",
                            Precio = 850.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 5,
                            Marca = "Continental",
                            Nombre = "Refrigeradora",
                            Precio = 1150.00m,
                            Stock = 16
                        },
                        new
                        {
                            Id = 6,
                            Marca = "Mabe",
                            Nombre = "Cocina",
                            Precio = 450.00m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 7,
                            Marca = "GE",
                            Nombre = "Cocina",
                            Precio = 538.00m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 8,
                            Marca = "Electrolux",
                            Nombre = "Cocina",
                            Precio = 599.00m,
                            Stock = 11
                        },
                        new
                        {
                            Id = 9,
                            Marca = "Indurama",
                            Nombre = "Cocina",
                            Precio = 538.00m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 10,
                            Marca = "Continental",
                            Nombre = "Cocina",
                            Precio = 625.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 11,
                            Marca = "Mabe",
                            Nombre = "Microondas",
                            Precio = 178.00m,
                            Stock = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
